version: "3"

services:
  lcgan:
    build: .
    ports:
      - 8085:8085
    volumes:
      - "~/:/work/"
    tty: true
    stdin_open: true
    deploy:
            resources:
                    reservations:
                            devices:
                                - driver: nvidia
                                  count: 1
                                  capabilities: [utility, compute, video, gpu]
    #runtime: nvidia
    #environment:
    #  - NVIDIA_VISIBLE_DEVICES=all
